name: Upload ADK Docs to Vertex AI Search

on:
  # Runs once per day at 16:00 UTC
  schedule:
   - cron: '00 16 * * *'
  # Manual trigger for testing and fixing
  workflow_dispatch:

jobs:
  upload-adk-docs-to-vertex-ai-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone adk-docs repository
        run: git clone https://github.com/google/adk-docs.git /tmp/adk-docs

      - name: Clone adk-python repository
        run: git clone https://github.com/google/adk-python.git /tmp/adk-python

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.ADK_GCP_SA_KEY }}'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install google-adk markdown google-cloud-storage google-cloud-discoveryengine

      - name: Run Answering Script
        env:
          GITHUB_TOKEN: ${{ secrets.ADK_TRIAGE_AGENT }}
          GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT }}
          GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION }}
          VERTEXAI_DATASTORE_ID: ${{ secrets.VERTEXAI_DATASTORE_ID }}
          GOOGLE_GENAI_USE_VERTEXAI: 1
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          ADK_DOCS_ROOT_PATH: /tmp/adk-docs
          ADK_PYTHON_ROOT_PATH: /tmp/adk-python
          PYTHONPATH: contributing/samples
        run: python -m adk_answering_agent.upload_docs_to_vertex_ai_search
